[package]
name = "shared_types"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = { version = "1.0.92", features = ["proc-macro"] }
quote = "1.0.38"
syn = { version = "2.0.96", features = ["parsing", "full"] }
shared_macros = { path = "shared_macros" }
